### ISSUE TITLE
IoS 6.5.2  -- Crashed: com.apple.NSURLSession-delegate

### ISSUE THREAD

**Issue by ghost** [twilio/twilio-voice-ios#116] opened 2023-06-22 23:46 UTC
We are seeing this intermittent crash of the 6.5.2 iOS version.   Was checking to see if anyone had seen this in the past or has any additional info.  

No calls are present.  The crash happens when the users starts the App.  

We have seen these iOS versions with the issue.  
16.0.2
16.4.1
16.5

Iphone 12, 13, and 14.   

We have been researching com.apple.NSURLSession-delegate, but not seeing anything specific to this issue.   

THX

Crashed: com.apple.NSURLSession-delegate
0  libobjc.A.dylib                0x3a7c objc_retain + 16
1  libobjc.A.dylib                0x3a7c objc_retain_x0 + 16
2  CoreFoundation                 0x806d4 __NSDictionaryI_new + 480
3  CoreFoundation                 0x252fc +[NSDictionary dictionaryWithObjects:forKeys:count:] + 52
4  TwilioVoice                    0x2d7d8 +[TVOEndpointAnalyticsEvent eventWithName:group:level:payload:] + 143 (TVOEndpointAnalyticsEvent.m:143)
5  TwilioVoice                    0x196dc -[TVONotificationClient publishEventWithError:] + 340 (TVONotificationClient.mm:340)
6  TwilioVoice                    0x1887c __71-[TVONotificationClient performEndpointRegistrationTaskWithCompletion:]_block_invoke.139 + 197 (TVONotificationClient.mm:197)
7  CFNetwork                      0x20048 CFURLRequestSetMainDocumentURL + 2972
8  CFNetwork                      0x2fd30 _CFNetworkErrorCopyLocalizedDescriptionWithHostname + 13648
9  libdispatch.dylib              0x2320 _dispatch_call_block_and_release + 32
10 libdispatch.dylib              0x3eac _dispatch_client_callout + 20
11 libdispatch.dylib              0xb534 _dispatch_lane_serial_drain + 668
12 libdispatch.dylib              0xc0d8 _dispatch_lane_invoke + 436
13 libdispatch.dylib              0x16cdc _dispatch_workloop_worker_thread + 648
14 libsystem_pthread.dylib        0xddc _pthread_wqthread + 288
15 libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x118c __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

**Comment by bobiechen-twilio** [comment] 2023-06-22 23:48
Hi @smiles7566a 

Thanks for reaching out. Is it possible for you to check if any of `CFBundleName`, `CFBundleIdentifier`, `CFBundleShortVersionString` and `CFBundleVersion` is empty in the application's Info.plist file?

**Comment by pjechris** [comment] 2023-07-24 09:01
Hey @bobiechen-twilio,

I also see this crash but way prior last SDK version.

I checked my `Info.plist` and all those keys have a value.

Note that the crash is random: it doesn't happen everytime.

If it can help I also have an opened a twilio bug ticket (12522983) about this subject.

**Comment by bobiechen-twilio** [comment] 2024-05-10 18:42
Fixed in 6.9.1 release. Feel free to reach out if you see similar issues. Thanks!

**Closed as completed by bobiechen-twilio** 2024-05-10 18:42 UTC

**Comment by loftytommyliu** [comment] 2025-05-20 10:33
@bobiechen-twilio The issue still occurs in SDK version 6.13.0. There's a dangling pointer since released objects are being accessed after deallocation. Please confirm if this has been properly fixed.

For reference, I executed the registration process three times during app startup, but I'm not sure if that's the cause of the dangling pointer.

```objc
[TwilioVoiceSDK registerWithAccessToken:kAccessToken
                                    deviceToken:cachedDeviceToken
                                     completion:^(NSError *error) {
      if (error) {
          NSLog(@"An error occurred while registering: %@", [error localizedDescription]);
      } else {
          NSLog(@"Successfully registered for VoIP push notifications.");
          
          // Save the device token after successfully registered.
          [[NSUserDefaults standardUserDefaults] setObject:cachedDeviceToken forKey:kCachedDeviceToken];
          
          /**
          * The TTL of a registration is 1 year. The TTL for registration for this device/identity
          * pair is reset to 1 year whenever a new registration occurs or a push notification is
          * sent to this device/identity pair.
          */
          [[NSUserDefaults standardUserDefaults] setObject:[NSDate date] forKey:kCachedBindingTime];
      }
}];
```

**Comment by bobiechen-twilio** [comment] 2025-05-20 16:56
@loftytommyliu 

Could you please provide the stack trace of the issue you are seeing?
Is this reproducible in the local dev environment? If so could you please provide the exact steps?

Thanks.

**Comment by loftytommyliu** [comment] 2025-05-20 23:47
@bobiechen-twilio 

The stack trace is the same as the one provided by ghost.
```
Crashed: com.apple.NSURLSession-delegate
0 libobjc.A.dylib 0x1458 objc_retain + 16
1 libobjc.A.dylib 0x1458 objc_retain_x0 + 16
2 CoreFoundation 0x1d94 __NSDictionaryI_new + 412
3 CoreFoundation 0x4e22c +[NSDictionary dictionaryWithObjects:forKeys:count:] + 52
4 TwilioVoice 0x36cb8 +[TVOEndpointAnalyticsEvent eventWithName:group:level:payload:] + 153 (TVOEndpointAnalyticsEvent.m:153)
5 TwilioVoice 0x21894 -[TVONotificationClient publishEventWithError:] + 340 (TVONotificationClient.mm:340)
6 TwilioVoice 0x20bf8 __71-[TVONotificationClient performEndpointRegistrationTaskWithCompletion:]_block_invoke.34 + 197 (TVONotificationClient.mm:197)
7 CFNetwork 0x30750 __40-[__NSURLSessionLocal taskForClassInfo:]_block_invoke + 508
8 CFNetwork 0x30510 __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke_2 + 160
9 libdispatch.dylib 0x1aac _dispatch_call_block_and_release + 32
10 libdispatch.dylib 0x1b584 _dispatch_client_callout + 16
11 libdispatch.dylib 0xa2d0 _dispatch_lane_serial_drain + 740
12 libdispatch.dylib 0xade0 _dispatch_lane_invoke + 440
13 libdispatch.dylib 0x151dc _dispatch_root_queue_drain_deferred_wlh + 292
14 libdispatch.dylib 0x14a60 _dispatch_workloop_worker_thread + 540
15 libsystem_pthread.dylib 0x4660 _pthread_wqthread + 292
16 libsystem_pthread.dylib 0x19f8 start_wqthread + 8
```

This is a crash in the release environment, with over 341 occurrences so far and still increasing. It's hard to reproduce in the local environment—I’ve been trying, but it’s an intermittent crash. Most users crash right at launch. I’m not sure if it’s related to the multiple registrations.
