### ISSUE TITLE
Ongoing calls are killed when receiving a call from Twilio

### ISSUE THREAD

**Issue by ream88** [twilio/twilio-voice-ios#22] opened 2019-10-28 15:11 UTC
We're currently facing a major outage for our iOS app as incoming calls from Twilio kill any ongoing callkit calls. The user is presented the following screen below:

![IMG_3255](https://user-images.githubusercontent.com/14321/67688926-e2fcaa00-f99a-11e9-89ea-85aa163b6271.PNG)

Thinking the fault was on our side I basically recoded the Twilio related part of our app based on https://github.com/twilio/voice-quickstart-swift, however to no success. I then proceeded to compile the quickstart example without major changes besides communicating with our API to obtain the required tokens. And the same result: **Incoming Twilio calls are killing existing calls**.
This happens on iOS 13, versions prior to iOS 13 seem to be unaffected.

### Steps to Reproduce

1. Get the TwilioVoiceQuickStart app to work
2. Start some random call via the Phone.app
3. Start a call to the TwilioVoiceQuickStart app

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

5.0.0

#### Xcode

11.1

#### iOS Version

13.1.3

#### iOS Device

iPhone 11 Pro

**Comment by bobiechen-twilio** [comment] 2019-10-28 16:48
Thanks @ream88 for reporting the issue and sharing debugging information.
While we are investigating with the steps you provided, can you also share the SDK log when this is happening?

Thanks,
-bobie

**Comment by ream88** [comment] 2019-10-28 17:01
@bchen-twilio what is the best way to do so? Paste the console output from Xcode here?

**Comment by bobiechen-twilio** [comment] 2019-10-28 17:10
@ream88 Yes, the Xcode debugging log with SDK `TVOLogLevelTrace` should work and please remove any sensitive credentials before posting here.

-bobie

**Comment by ream88** [comment] 2019-10-28 17:19
Thats everything: 
```2019-10-28 18:16:31.331637+0100 SwiftVoiceQuickstart[3634:956540] Twilio Voice Version: 5.0.0
2019-10-28 18:16:31.523848+0100 SwiftVoiceQuickstart[3634:956540] providerDidBegin
2019-10-28 18:16:31.523911+0100 SwiftVoiceQuickstart[3634:956540] pushRegistry:didUpdatePushCredentials:forType:
2019-10-28 18:16:33.037255+0100 SwiftVoiceQuickstart[3634:956540] TRACE:Twilio:[Platform]:Registering for Twilio push notifications
Access Token:	[REDACTED]
VoIP Registry Token:	[REDACTED]
2019-10-28 18:16:33.041198+0100 SwiftVoiceQuickstart[3634:956540] DEBUG:Twilio:[Platform]:Register for push notifications.
2019-10-28 18:16:33.691003+0100 SwiftVoiceQuickstart[3634:956759] DEBUG:Twilio:[Platform]:Completed registration request.
2019-10-28 18:16:33.691462+0100 SwiftVoiceQuickstart[3634:956540] INFO:Twilio:[Platform]:Inside register:deviceToken:completion:, registered for Twilio push notifications.
2019-10-28 18:16:33.691666+0100 SwiftVoiceQuickstart[3634:956540] Successfully registered for VoIP push notifications.
2019-10-28 18:17:04.091893+0100 SwiftVoiceQuickstart[3634:956540] Can't end BackgroundTask: no background task exists with identifier 1 (0x1), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.
```

**Comment by ream88** [comment] 2019-10-28 17:20
Maybe this info helps you: The ongoing call is canceled and the incoming call does NEVER start to ring.

**Comment by bobiechen-twilio** [comment] 2019-10-28 20:48
Hi @ream88 

Just want to let you know that I was able to reproduce the same call failure with iOS 13.1.3 device and I am looking into the device log captured by the Mac OS Console app. It's a very long log and I probably need some time to figure out what caused the problem.

-bobie

**Comment by ream88** [comment] 2019-10-28 21:16
That’s good news 😊

**Comment by bobiechen-twilio** [comment] 2019-10-30 22:37
Hi @ream88 

Although we haven't gotten any luck in terms of reaching to a solution for this issue, I found that this problem only happens when the app is built with Xcode 11 and running on iOS 13 (my device is on 13.1.3). I ran the same steps on the same device but with the app built from Xcode 10 and couldn't reproduce the call failure. Our observations match this post: https://stackoverflow.com/questions/58117066/native-cellular-call-fails-on-voip-incoming-call-in-ios-13

Also from the device log I found a message MobilePhone Disconnecting call with TUCallDisconnectedReasonComponentCrashed: <private>, but the context in the log doesn't really provide the reason why it "crashed". So far there hasn't been any discussion about TUCallDisconnectedReasonComponentCrashed on the internet.

I found someone posted basically the same problem in the Apple developer forum and added our findings in that thread hoping to get more attention: https://forums.developer.apple.com/message/384381#384381

Unfortunately no solution yet but would like to share some updates.

Cheers,
-bobie

**Comment by ream88** [comment] 2019-10-31 10:14
Thx a lot for the investigation! 😊 So your suggestion is to build the App with Xcode 10? I'm not sure if this is even possible as our App build with Xcode 11 is already in the wild.

**Comment by bobiechen-twilio** [comment] 2019-10-31 18:45
Hi @ream88 

Since Apple is mandating developer to submit their apps using Xcode 11 in 2020, we think it would make more sense to ask Apple to address the issue in the latest Apple SDK, therefore we have filed a Feedback ticket to Apple with the investigation information we gathered including device logs and screenshots. We will keep an eye on this and hopefully the fix won't come too late.

Cheers,
-bobie

**Comment by bobiechen-twilio** [comment] 2019-11-11 20:56
Hi @ream88,

Although we haven't received anything from the Feedback ticket we filed last week, I tried running the same steps with Xcode 11.2 (11B52) and the calls seemed to work on iOS 13.2 & 13.2.2 devices. Previously I was using Xcode 11.0 and iOS 13.1.3.

I was able to interrupt both PSTN outbound and PSTN inbound calls with VoIP incoming calls and continue the calls after the interruption without failing the active PSTN calls.

We will do more validations but can you also give Xcode 11.2 + iOS 13.2+ a try and see if the problem is still happening?

Thanks,
-bobie

**Comment by bobiechen-twilio** [comment] 2019-11-19 00:51
Hi @ream88,

The original issue seems to be fixed in the latest iOS/Xcode so I am going closing this ticket. Please feel free to reach out to us if you run into any problem using the Voice SDK.

Cheers,
-bobie

**Closed as completed by bobiechen-twilio** 2019-11-19 00:51 UTC
Labels: bug

**Comment by ream88** [comment] 2019-11-20 21:37
Yep, does indeed work now! Thx a lot for your help and all the great work you do! 😊

**Comment by muzammil-triffort** [comment] 2020-11-08 19:37
Is this working with Xcode 12 / iOS 14.1 ?

**Comment by bobiechen-twilio** [comment] 2020-11-09 20:21
@muzammil-triffort The Voice SDK is validated with the latest Xcode and iOS environment. Feel free to reach out if you see any issue using the SDK. Thanks.
