### ISSUE TITLE
voice call terminates when dial sound starts playing

### ISSUE THREAD

**Issue by geoter** [twilio/twilio-voice-ios#44] opened 2020-04-11 18:15 UTC
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Voice Guides](https://www.twilio.com/docs/api/video/ios)
>  * [Github Issues](https://github.com/twilio/twilio-voice-ios/issues)
>  * [Changelog](https://www.twilio.com/docs/api/voice-sdk/ios/changelog)
>
> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

I use this project as is. I haven't imported it into any of my projects.
When I start a call to another identity from my iPad, it rings once and terminates the call with error.
AVAudioSession setAggregatedIOPreference:error: Error Domain=NSOSStatusErrorDomain Code=560030580

### Steps to Reproduce

1. run on iPad mini 2 iOS 12.4.6
2. call another identity (leaving textfield empty works just fine.)
3. [Insert as many steps as needed]

#### Actual Behavior

[What actually happens]

#### Reproduces How Often

Every time I run it.

#### Logs

```
2020-04-11 21:14:26.765768+0300 SwiftVoiceQuickstart[1321:62320] callDidConnect:
2020-04-11 21:14:26.878318+0300 SwiftVoiceQuickstart[1321:62320] AVAudioSession setAggregatedIOPreference:error: Error Domain=NSOSStatusErrorDomain Code=560030580 "(null)"
2020-04-11 21:14:35.249848+0300 SwiftVoiceQuickstart[1321:62320] Call disconnected
2020-04-11 21:14:35.382777+0300 SwiftVoiceQuickstart[1321:62699] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C3.1:2][0x147dbcf70] get output frames failed, state 8196
2020-04-11 21:14:35.426025+0300 SwiftVoiceQuickstart[1321:62699] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C3.1:2][0x147dbcf70] get output frames failed, state 8196
2020-04-11 21:14:35.427894+0300 SwiftVoiceQuickstart[1321:62699] TIC Read Status [3:0x0]: 1:57
2020-04-11 21:14:35.428822+0300 SwiftVoiceQuickstart[1321:62699] TIC Read Status [3:0x0]: 1:57
2020-04-11 21:14:35.439918+0300 SwiftVoiceQuickstart[1321:62320] provider:didDeactivateAudioSession:
```

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

5.3.0

#### Xcode

11.4

#### iOS Version

12.4.6

#### iOS Device

iPad mini 2

**Comment by bobiechen-twilio** [comment] 2020-04-13 16:48
Hi @geoter 

Thanks for reporting the issue. Can you provide a Twilio Call SID when this happens? Also a `.trace` level of SDK log would be helpful for debugging what happened.

-bobie

**Comment by geoter** [comment] 2020-04-14 06:21
I don't know how to get these .trace logs you are mentioning. Could you please guide me?
The app doesn't crash, if this helps. So can I get these logs you are saying?

**Comment by geoter** [comment] 2020-04-14 18:14
I haven't figured out exactly but it had to do with UserDefaults saving the identity and causing a problem. Probably two identities saved in the same device.

**Comment by bobiechen-twilio** [comment] 2020-04-14 20:27
Hi @geoter 

Please use the `logLevel` property of `TwilioVoice`
```
  [TwilioVoice setLogLevel:TVOLogLevelTrace];
```

For the Call SIDs, you can find the Twilio Call SIDs in the [developer console](https://www.twilio.com/console/voice/calls/logs) if the call made it through or you can also use the `TVOCall.sid` property to retrieve the Call SID when you receive the `callDidConnect:` callback.

**Comment by bobiechen-twilio** [comment] 2020-04-29 18:26
Hi @geoter 

How are things? Are you still experiencing the issue you originally reported? Feel free to provide us SDK logs and Twilio Call SIDs in case you are still seeing the problem in your app.

Thanks,
bobie

**Comment by geoter** [comment] 2020-04-29 18:30
Hi @bchen-twilio. The problem was iOS side and had to do with UserDefaults saving user info from previous sessions of the app. When I removed it I worked just fine. I am not sure what exactly is going wrong.

**Comment by bobiechen-twilio** [comment] 2020-04-29 18:35
Thanks for the update @geoter. Since it's not caused by the SDK I am going to close the issue for now. You are more than welcome to reach out to us if you run into any problem using the SDK in the future.

**Closed as completed by bobiechen-twilio** 2020-04-29 18:35 UTC

**Comment by vpcunha** [comment] 2020-05-11 12:29
I'm running into this same error:
AVAudioSession setAggregatedIOPreference:error: Error Domain=NSOSStatusErrorDomain Code=560030580
But in my case the app is working fine. I can make calls, but I always get this message in the console after the callDidConnect: message.

**Comment by rcfrias** [comment] 2022-09-21 16:08
Me too, apparently this hasn't been solved yet.
